import type { Metadata } from 'next'
import './globals.css'
import Button from './ui/button'
import Script from 'next/script'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="light">
      <body className="main">
        {/* <Script id="theme-script" strategy="beforeInteractive">
          {`
          const item = localStorage.getItem('theme') || 'light';
          console.log(item)
          localStorage.setItem('theme', item);
          const classList = document.documentElement.classList.add(item)
          `}
        </Script> */}
        <script
          async
          dangerouslySetInnerHTML={{
            __html: `
          const item = localStorage.getItem('theme') || 'light';
          localStorage.setItem('theme', item); 
          if(item === 'dark') {
            if(document.documentElement.classList.contains('dark')){
            }else{
              document.documentElement.classList.add('dark')
            }
            document.documentElement.classList.remove('light')
          }else{
            if(document.documentElement.classList.contains('light')){
            }else{
              document.documentElement.classList.add('light')
            }
            document.documentElement.classList.remove('dark') 
          }
          `
          }}
        ></script>
        <Button></Button>
        {children}
      </body>
    </html>
  )
}
