import type { Metadata } from 'next'
import './globals.css'
import { headers } from 'next/headers'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  const nonce = headers().get('x-nonce') || ''

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${1 ? 'view-transition' : ''}`}>
        {/* 新增 */}
        <script
          nonce={nonce}
          async
          dangerouslySetInnerHTML={{
            __html: `
              const item = localStorage.getItem('theme') || 'light';
              document.documentElement.classList.toggle('dark', item === 'dark');
              document.documentElement.classList.toggle('light', item === 'light');
            `
          }}
        ></script>
        {children}
      </body>
    </html>
  )
}
