/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 *      
 */

/* eslint-disable */

                                 
                             
                                      
                                 

                                                 /*?{
  inject: ?((stuff: Object) => void)
};*/

                               

                                                   
                                                
                                         

                                      

                                     
                                         
 

// Flow hides the props of React$Element, this overrides it to unhide
// them for React internals.
// prettier-ignore
                                  
                                  
                                       
    
                     
            
                         
            
  

                           
                                  
                                    
                                       
                                                                                                        
                                  
  

// ReactFeatureFlags www fork
                                    
                              
 

// ReactFiberErrorDialog www fork
                                        
                                                                            
 

// EventListener www fork
                                
                           
             
                          
                   
                         
                        
                                        
               
                                                                              
                             
                          
                   
                         
                       
               
                            
                          
                   
                         
                       
               
       
    
 

                                                                    
                                                          
                      
  

                                                                
                                                            
                      
  

                              
                                                                     
                      
                 
                                  
                      
                        
                 
             
               
         
                             
                                   
          
                       
                         
                 
             
               
         
                             
          
                       
                         
                 
             
               
         
                             
          
                      
                         
                 
             
               
         
                             
          
                      
                     
                 
                                  
                      
 
                     
                                         
                                                          
    
 

                       
                                                                                
                                                                        
                                             
                                                                               
                                                 
                                                  
                                                
                                                 
                            
                          
                               
          
                                                                    
                                                    
                                                      
                             
                
                        
                 
                        
                            
           
        
            
           
                                                   
                                        
              
                     
                   
                       
   
                             
                                                
                                       
               
                     
                       
                                       
                     
   
 

                         
                                                 

                          
                     
                     
   

                                           
                     
   

                                            
                           
                            
   

                                  
                                                                   
                                                                  
                           
                           
                            
                                  
                      
   
                                             
                                            
                   
                                    
              
                
                             
                                         
              

                                   
                   
                                    
              
                                                                           

                                     
                   
                                    
              
                                                                             

                                               
                   
                                    
              
                   
                             
                                         
              

                                    
                   
                                    
              
                                                                            

                                                
                   
                                    
              
                    
                             
                                         
              

                                                    
                   
                                    
              
                        
                             
                                         
              
   
 

                               
                           
                                  
    
 

                                    
                  
                       
                                                                          
                            
 

                              
                                      
                    
                         
                                                                            
                              
   
 

                                      
                                
                       
                       
   
 

                  
       
                                                                             
            
  
